apiVersion: apps/v1
kind: Deployment
metadata:
  name: paid-dapp
  labels:
    app: dapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dapp
    spec:
      containers:
        - image: gcr.io/vivid-plateau-278712/paid-dapp:cicd-development-latest
          name: dapp
          ports:
            - containerPort: 80
