apiVersion: v1
kind: Service
metadata:
  name: paid-dapp-service
  labels:
    app: dapp-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: dapp
  type: LoadBalancer
